version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - google_scraper_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    image: google_scraper
    command: "python manage.py runserver 0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    restart: on-failure
    env_file: .env

volumes:
  google_scraper_data:
    external: true
